### ISSUE TITLE
중간에 어떤문제인지는 모르겠지만요

### ISSUE THREAD

**Issue by flesh7-7** [dc-creator/record-youtube#1]
![오류1](https://user-images.githubusercontent.com/80151104/110201836-7e176500-7ea8-11eb-9352-c513ee4d913c.PNG)
![오류2](https://user-images.githubusercontent.com/80151104/110201839-7f489200-7ea8-11eb-967b-a15b9a4f2ec2.PNG)
중간에 제가 잘 몰라서 문제가 생긴거 같은데
실행하면
name 'exit' is not defined
오류 발생
알 수 없는 오류가 발생했다면
logb1.txt 및 오류가 난 상황 등을
https://github.com/dc-creator/record-youtube/issues 에 올려주세요
이 프로그램은 10초 후에 종료됩니다
라고 뜹니다..

**Comment by tasoo-oos** [comment]
@flesh7-7 녹화가 끝나고 프로그램이 영상을 유투브에 업로드하려할 때 일어난 현상인가요?
저 부분이 글에 나와있긴 하지만 이 상황에선 굳이 실행을 하지 않아도 됩니다

**Comment by flesh7-7** [comment]
네 업로드할때의 상황입니다그리고 저 창이 계속 켜졌다가 꺼지고를반복합니다

**Comment by tasoo-oos** [comment]
@flesh7-7 오류인 것 같군요 제가 집에 가서 고치겠습니다

**Comment by flesh7-7** [comment]
"인터넷 창에서 구글 로그인 창이 뜹니다"이 추가로 오류인지 제 실수인지는 모르겠지만 실행하면 이부분부터 이어지지가 않습니다

**Comment by flesh7-7** [comment]
않습니다

**Comment by tasoo-oos** [comment]
@flesh7-7 패치가 끝났습니다 다시 시도해보세요

**Comment by tasoo-oos** [comment]
@flesh7-7 정상적으로 프로그램이 동작한다면 close with comment 버튼을 눌러주시기 바랍니다
