### ISSUE TITLE
유튜브 업로드용 프로그램 실행 시 오류 발생

### ISSUE THREAD

**Issue by unitek1** [dc-creator/record-youtube#2]
티스토리 링크에 있는 여러 인증 작업 및 client_secrests.json 작성이나 구글 api 설치도 완료했고, 유튜브 업로드 프로그램을 제 구글 계정과 연결하는 것까지 마쳤는데, 정작 실패하면서 로그를 확인하라더군요. 그 로그의 내용은 다음과 같습니다.

Traceback (most recent call last):
  File "upload_video.py", line 199, in <module>
    initialize_upload(youtube, args)
  File "upload_video.py", line 122, in initialize_upload
    media_body=MediaFileUpload(options.file, chunksize=-1, resumable=True)
  File "googleapiclient\_helpers.py", line 134, in positional_wrapper
  File "googleapiclient\http.py", line 566, in __init__
OSError: [Errno 22] Invalid argument: 'D:\\ZDownload\\record-youtube-master\\20210307 고차비 2021-03-06T09:28:41Z.mp4'

그리고 master.exe가 실행시킨 autorecord.exe의 내용도 혹시 모르니 같이 첨부합니다.
![image](https://user-images.githubusercontent.com/80166730/110213074-d6b72400-7ee1-11eb-8be3-1d7f7d60841d.png)

**Comment by tasoo-oos** [comment]
@unitek1 최신버전을 다운받아주세요

**Comment by unitek1** [comment]
> @unitek1 최신버전을 다운받아주세요

다시 파일을 받아봤는데 여전히 같은 문제를 겪고 있습니다.

**Comment by tasoo-oos** [comment]
@unitek1 최신버전에서의 autorecord.exe 화면을 캡쳐해서 첨부해주세요. 현재 가지고 있는 정보만으로는 버그를 고치기 어렵습니다

**Comment by dc-creator** [comment]
@unitek1 최신버전에서의 autorecord.exe 화면을 캡쳐해서 첨부해주세요. 현재 가지고 있는 정보만으로는 버그를 고치기 어렵습니다

**Comment by unitek1** [comment]
> @unitek1 최신버전에서의 autorecord.exe 화면을 캡쳐해서 첨부해주세요. 현재 가지고 있는 정보만으로는 버그를 고치기 어렵습니다

![image](https://user-images.githubusercontent.com/80166730/110412987-74704600-80d0-11eb-847a-ec39ad408f4b.png)
이와 같이 뜨고, 그후 upload_video.exe가 실행되는데, 그 후 upload_video.exe가 다음과 같은 오류를 출력합니다.
![image](https://user-images.githubusercontent.com/80166730/110413132-b13c3d00-80d0-11eb-9e3b-bfb4ba304d5e.png)

**Comment by tasoo-oos** [comment]
@unitek1 어떤 경로로 다운받으셨나요?
현재 최신버전에서는 파일명이 무작위로 뽑은 20자의 영소문자.mp4 여야 합니다
세 exe 파일을 모두 지운 뒤  https://github.com/dc-creator/record-youtube 에 들어가 exe 파일들을 다시 다운받아주시기 바랍니다

**Comment by unitek1** [comment]
이제 정상적으로 되는 것 같습니다. 녹화중인 영상의 이름도 영소문자 나열로 되어있네요. 기존의 문제점은 업데이트 버전을 다운받을 때 기존 exe를 지우지 않고 덮어씌워서 발생한 문제였던 거 같습니다.

**Comment by tasoo-oos** [comment]
@unitek1 해결되었다니 다행입니다
