### ISSUE TITLE
녹화는 되는데 업로드가 안됩니다.

### ISSUE THREAD

**Issue by hyangun617** [dc-creator/record-youtube#3]
앞선 티스토리의 글에서 하는것처럼 손수 명령어를 입력해서 실행할 경우에는 영상이 업로드가 됩니다.
권한 부여도 다 했습니다.

앞서 제가 직접 방송을 켜서 테스트를 하는 도중에 문제가 발견되었습니다.
master.exe 를 실행할 경우에, 녹화는 정상적으로 진행이 되지만 녹화가 종료되고 난 뒤에 업로드 exe를 실행하는데 문제가 있습니다.

Traceback (most recent call last):
  File "upload_video.py", line 199, in <module>
    initialize_upload(youtube, args)
  File "upload_video.py", line 122, in initialize_upload
    media_body=MediaFileUpload(options.file, chunksize=-1, resumable=True)
  File "googleapiclient\_helpers.py", line 134, in positional_wrapper
  File "googleapiclient\http.py", line 566, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'zttfiojhhdjuipaxrofp.mp4'

왜이럴까요?

![123123](https://user-images.githubusercontent.com/80374772/110572994-d34fc100-819d-11eb-880a-01f2bce889b1.png)

**Comment by hyangun617** [comment]
아. 녹화가 종료될때 업로드 exe파일이 여러번 실행되면서 오류문구만 출력되는 거였네요.
착각했습니다. 업로드는 되있네요

**Comment by tasoo-oos** [comment]
@hyangun617 

프로그램이 방송이 켜져있는지를 판단할 때는 트위치에서 자체적으로 제공하는 api를 사용합니다
그런데 그 api 는 업데이트가 즉시 이루어지지는 않기에 사용자분의 경우처럼 주기를 너무 짧게 설정할경우 방송은 꺼져있는데 프로그램은 방송이 켜져있는것으로 인식을 해 정작 녹화는 되지 않는 상황이 일어나는 것입니다. 

사용자분께서는 당분간 주기를 15초 이상으로 설정하여 사용해주시기 바랍니다
