### ISSUE TITLE
api 스팸처리

### ISSUE THREAD

**Issue by Hemiptelea** [dc-creator/record-youtube#5]
영상을 올리다 보면 유튜브측에서 api가 스팸영상(지속적으로 영상을 올리는행위)를 반복한다고 비공개로 돌려버리는데 해결방법이 있을까요ㅜ

**Comment by Hemiptelea** [comment]
https://support.google.com/youtube/answer/6388033?hl=ko&ref_topic=7071641

알아보니까 api audit 처리를 개발자분께서 해주셔야 하는거같아요..

**Comment by tasoo-oos** [comment]
@queechy 죄송하지만 제가 지금 바빠서 적어도 11월 중순까지는 프로그램을 건드릴 수 없는 상황입니다....
정말 급하시다면 올려둔 소스코드를 직접 수정하시는 것을 추천드립니다
