### ISSUE TITLE
녹화가 안됨

### ISSUE THREAD

**Issue by asdf1115** [dc-creator/record-youtube#6]
![465321 (2)](https://user-images.githubusercontent.com/50540451/113813619-32a7ed80-97ab-11eb-9ffc-c902c3f3b6b3.PNG)
실행시키면 이렇게 녹화가 안된다는데 왜그런지 아시나요?
[loga1.txt](https://github.com/dc-creator/record-youtube/files/6269138/loga1.txt)

**Comment by tasoo-oos** [comment]
streamlink 자체 패치가 있었던 모양이군요
제가 시간이 없는지라 프로그램 수정을 할 수 없는 점 양해부탁드립니다...
